# Generated by Django 2.2.6 on 2019-12-06 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeShareModel',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='untitled', max_length=20)),
                ('code', models.TextField(max_length=5000)),
                ('language', models.CharField(default='python', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
    ]
